name: Update Deno Dependencies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Update Dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts ./import_map.json
      - name: Run Tests
        run: |
          deno task test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(deps): Update dependencies"
          body: |
            Automated changes created by workflow run [${{github.run_id}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}).
          commit-message: "chore(deps): Update dependencies"
          delete-branch: true
